# Generated by Django 3.2.21 on 2023-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_reviews', '0003_auto_20231010_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created_on',
            field=models.DateTimeField(default='2023-10-10 09:53:53'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_updated_on',
            field=models.DateTimeField(default='2023-10-10 09:53:53'),
        ),
    ]
