# Generated by Django 3.2.21 on 2023-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_auto_20231023_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(default="2023-10-24 19:26:29"),
        ),
    ]
