# Generated by Django 3.2.21 on 2023-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="percentage",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
